In [1]:
# Libraries

import pandas as pd

In [2]:
# Set better options to allow viewing more of the dataframe

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
# Import csv

king_raw = pd.read_csv('../data/King_County.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (9,17,45,52,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
king_raw.head()

   OBJECTID  MAJOR MINOR         PIN     COMMENTS SITETYPE    SITEID ADDR_HN ADDR_PD ADDR_PT ADDR_SN ADDR_ST ADDR_SD  ADDR_NUM        ADDR_FULL    FULLNAME     ZIP5 PLUS4 CTYNAME POSTALCTYNAME        LAT         LON       POINT_X        POINT_Y COUNTY KROLL   KCTP_CITY KCTP_STATE       PLSS               PROP_NAME   PLAT_NAME        PLAT_LOT PLAT_BLOCK   LOTSQFT  LEVYCODE LEVY_JURIS NEW_CONSTR TAXVAL_RSN  APPRLNDVAL  APPR_IMPR  TAX_LNDVAL  TAX_IMPR   ACCNT_NUM  KCTP_TAXYR UNIT_NUM BLDG_NUM CONDOSITUS QTS   SEC   TWP  RNG  PRIMARY_ADDR ANNEXING_CITY PAAUNIQUENAME PROPTYPE ALIAS1 ALIAS2 KCA_ZONING  KCA_ACRES                                          LEGALDESC  PREUSE_CODE                                        PREUSE_DESC  Shape_Length     Shape_Area
0         1     20  0001  0000200001          NaN      NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN       NaN              NaN         NaN      NaN   NaN    KENT           NaN        NaN         NaN           NaN            NaN    NaN   351  FORT WORHT         TX  NW36-23-4            RAILROAD R/W  ADAMS # 43  000020            0001     366775.0    1514.0       KENT          N               366800.0        0.0    366800.0       0.0  20000105.0      2019.0      NaN      NaN        NaN  NW  36.0  23.0  4.0             1           NaN           NaN        C    NaN    NaN         M2   8.419995  HENRY ADAMS DONATION CLAIM NO 43 PORTION HENRY...        332.0  Right of Way/Utility, Road                    ...   4889.930132  367602.325773
1         2     20  0003  0000200003          NaN      NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN       NaN              NaN         NaN      NaN   NaN    KENT           NaN        NaN         NaN           NaN            NaN    NaN   351     TUKWILA         WA  NW36-23-4      VACANT-UNBUILDABLE  ADAMS # 43                               5400.0    9010.0        NaN                               0.0        0.0         0.0       0.0  20000303.0      2019.0      NaN      NaN        NaN  NW  36.0  23.0  4.0             1           NaN           NaN        C    NaN    NaN      GC-MU   0.123967  ADAMS HENRY-D C # 43 PORTION OF E 1/2 OF NW 1/...        316.0  Vacant(Industrial)                            ...    330.703714    5453.966925
2         3     20  0006  0000200006  ALI fallout       R1  604745.0    7211       S     NaN   180TH      ST     NaN    7211.0  7211 S 180TH ST  S 180TH ST  98032.0  1014    KENT          KENT  47.441020 -122.242984  1.291591e+06  164066.341940   KING   351    BELLEVUE         WA  NW36-23-4     Beauty Shop and SFR  ADAMS # 43                               6011.0    1514.0       KENT          N               120200.0    63400.0    120200.0   63400.0  20000600.0      2019.0      NaN      NaN        NaN  NW  36.0  23.0  4.0             1           NaN           NaN        C    NaN    NaN      GC-MU   0.137994  ADAMS HENRY-D C # 43              W 50 FT OF E...        106.0  Office Building                               ...    340.002037    6000.064501
3         4     20  0007  0000200007          NaN       C1  600178.0    7209       S     NaN   180TH      ST     NaN    7209.0  7209 S 180TH ST  S 180TH ST  98032.0  1014    KENT          KENT  47.440974 -122.243141  1.291552e+06  164050.203849   KING   351    BELLEVUE         WA  NW36-23-4           NW Aesthetics  ADAMS # 43                               7200.0    1514.0       KENT          N               144000.0   183100.0    144000.0  183100.0  20000709.0      2019.0      NaN      NaN        NaN  NW  36.0  23.0  4.0             1           NaN           NaN        C    NaN    NaN      GC-MU   0.165289  ADAMS HENRY-D C # 43              W 60 FT OF E...        106.0  Office Building                               ...    360.002087    7200.080078
4         5     20  0008  0000200008          NaN      NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN       NaN              NaN         NaN      NaN   NaN    KENT           NaN        NaN         NaN           NaN            NaN    NaN   351    BELLEVUE         WA  NW36-23-4  VACANT COMMERCIAL LAND  ADAMS # 43                               5947.0    1514.0       KENT          N               118900.0        0.0    118900.0       0.0  20000808.0      2019.0      NaN      NaN        NaN  NW  36.0  23.0  4.0             1           NaN           NaN        C    NaN    NaN      GC-MU   0.136524  ADAMS HENRY-D C # 43              W 60 FT OF E...        309.0  Vacant(Commercial)                            ...    317.359849    6068.041700

In [5]:
# Fill the zipcode nulls with 0 so we can turn it into an int
king_raw.ZIP5.fillna(0, inplace=True)

In [6]:
# Set to int
king_raw['ZIP5'] = king_raw.ZIP5.astype(int)

In [7]:
# Double check
king_raw.dtypes

OBJECTID           int64
MAJOR              int64
MINOR             object
PIN               object
COMMENTS          object
SITETYPE          object
SITEID           float64
ADDR_HN           object
ADDR_PD           object
ADDR_PT           object
ADDR_SN           object
ADDR_ST           object
ADDR_SD           object
ADDR_NUM         float64
ADDR_FULL         object
FULLNAME          object
ZIP5               int64
PLUS4             object
CTYNAME           object
POSTALCTYNAME     object
LAT              float64
LON              float64
POINT_X          float64
POINT_Y          float64
COUNTY            object
KROLL             object
KCTP_CITY         object
KCTP_STATE        object
PLSS              object
PROP_NAME         object
PLAT_NAME         object
PLAT_LOT          object
PLAT_BLOCK        object
LOTSQFT          float64
LEVYCODE         float64
LEVY_JURIS        object
NEW_CONSTR        object
TAXVAL_RSN        object
APPRLNDVAL       float64
APPR_IMPR        float64
TAX_LNDVAL       float64
TAX_IMPR         float64
ACCNT_NUM        float64
KCTP_TAXYR       float64
UNIT_NUM          object
BLDG_NUM          object
CONDOSITUS        object
QTS               object
SEC              float64
TWP              float64
RNG              float64
PRIMARY_ADDR       int64
ANNEXING_CITY     object
PAAUNIQUENAME     object
PROPTYPE          object
ALIAS1            object
ALIAS2            object
KCA_ZONING        object
KCA_ACRES        float64
LEGALDESC         object
PREUSE_CODE      float64
PREUSE_DESC       object
Shape_Length     float64
Shape_Area       float64
dtype: object

In [21]:
# Use only the affected zip codes

king_zips = king_raw[(king_raw['ZIP5'] == 98022) | 
         (king_raw['ZIP5'] == 98092) | 
         (king_raw['ZIP5'] == 98001) |
         (king_raw['ZIP5'] == 98047) |
         (king_raw['ZIP5'] == 98003)]

In [22]:
dropcolumns = ['OBJECTID', 'MAJOR', 'MINOR', 'PIN', 'COMMENTS', 'SITETYPE', 'SITEID'
               , 'POINT_X', 'POINT_Y', 'COUNTY', 'KROLL',
       'KCTP_CITY', 'KCTP_STATE', 'PLSS', 'PROP_NAME', 'PLAT_NAME', 'PLAT_LOT',
       'PLAT_BLOCK', 'LOTSQFT', 'LEVYCODE', 'LEVY_JURIS', 'NEW_CONSTR','TAXVAL_RSN', 
       'ACCNT_NUM', 'KCTP_TAXYR', 'UNIT_NUM', 'BLDG_NUM', 'CONDOSITUS', 'QTS',
       'SEC', 'TWP', 'RNG', 'PRIMARY_ADDR', 'ANNEXING_CITY', 'PAAUNIQUENAME',
       'PROPTYPE', 'ALIAS1', 'ALIAS2', 'KCA_ZONING', 'KCA_ACRES', 'LEGALDESC',
       'PREUSE_CODE', 'PREUSE_DESC', 'Shape_Length', 'Shape_Area', 'ADDR_SN',
       'ADDR_ST','ADDR_SD', 'ADDR_HN','ADDR_PD','ADDR_PT','ADDR_NUM', 'FULLNAME']

In [23]:
# Drop unwanted columns

king_zips.drop(columns=dropcolumns, inplace=True)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [25]:
king_zips.head()

       ADDR_FULL   ZIP5 PLUS4 CTYNAME POSTALCTYNAME        LAT         LON  APPRLNDVAL   APPR_IMPR  TAX_LNDVAL    TAX_IMPR
28  2108 B ST NW  98001  1624  AUBURN        AUBURN  47.327354 -122.231053   5115900.0  20709100.0   5115900.0  20709100.0
48  5 14TH ST NW  98001  4000  AUBURN        AUBURN  47.320530 -122.229260    672700.0    827600.0    672700.0    827600.0
58  9 14TH ST NW  98001  4000  AUBURN        AUBURN  47.320538 -122.230934   1324800.0   4961600.0   1324800.0   4961600.0
62  9 16TH ST NW  98001  1613  AUBURN        AUBURN  47.323713 -122.231410    682200.0   6711900.0    682200.0   6711900.0
65  8 16TH ST NW  98001  1616  AUBURN        AUBURN  47.322836 -122.231380   2810800.0   4377000.0   2810800.0   4377000.0

In [26]:
king_zips.shape

(38559, 11)

In [27]:
king_zips.isna().sum()

ADDR_FULL            0
ZIP5                 0
PLUS4              704
CTYNAME          14392
POSTALCTYNAME      470
LAT                  0
LON                  0
APPRLNDVAL         152
APPR_IMPR          152
TAX_LNDVAL         152
TAX_IMPR           152
dtype: int64

In [28]:
# drop null tax values, as they're needed

king_zips.dropna(subset=['APPR_IMPR','TAX_LNDVAL','TAX_IMPR'], inplace=True)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [30]:
king_zips.isna().sum()

ADDR_FULL            0
ZIP5                 0
PLUS4              675
CTYNAME          14380
POSTALCTYNAME      445
LAT                  0
LON                  0
APPRLNDVAL           0
APPR_IMPR            0
TAX_LNDVAL           0
TAX_IMPR             0
dtype: int64

In [31]:
king_zips.shape

(38407, 11)

I don't care about these other nulls, as we have the latitude and longitude to determine if they are in the affected zones, and a value to go along with them

In [32]:
# Drop any duplicates based on lattitude and longitude
king_zips.drop_duplicates(subset = ['LAT','LON'], inplace=True)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [33]:
# reset index

king_zips.reset_index(drop=True, inplace=True)

In [34]:
king_zips.head()

      ADDR_FULL   ZIP5 PLUS4 CTYNAME POSTALCTYNAME        LAT         LON  APPRLNDVAL   APPR_IMPR  TAX_LNDVAL    TAX_IMPR
0  2108 B ST NW  98001  1624  AUBURN        AUBURN  47.327354 -122.231053   5115900.0  20709100.0   5115900.0  20709100.0
1  5 14TH ST NW  98001  4000  AUBURN        AUBURN  47.320530 -122.229260    672700.0    827600.0    672700.0    827600.0
2  9 14TH ST NW  98001  4000  AUBURN        AUBURN  47.320538 -122.230934   1324800.0   4961600.0   1324800.0   4961600.0
3  9 16TH ST NW  98001  1613  AUBURN        AUBURN  47.323713 -122.231410    682200.0   6711900.0    682200.0   6711900.0
4  8 16TH ST NW  98001  1616  AUBURN        AUBURN  47.322836 -122.231380   2810800.0   4377000.0   2810800.0   4377000.0

In [35]:
king_zips.shape

(38406, 11)

In [36]:
king_zips.to_csv('../data/kingvalues.csv')